spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update #처음시작할때는 create로 바꿔야함
    show-sql: true
server:
  port: 8080